// Licensed to the .NET Foundation under one or more agreements.
// The .NET Foundation licenses this file to you under the MIT license.

namespace SampleApi;

/// <summary>
/// Represents a customer entity in the system, serving as the primary domain model
/// for all customer-related operations including creation, retrieval, and segmentation.
/// </summary>
/// <remarks>
/// A <see cref="Customer"/> is the aggregate root for customer data. Every customer
/// is assigned a globally unique <see cref="Id"/> at creation time and must have a
/// non-empty <see cref="FullName"/>. Customers are active by default and can be
/// deactivated through <see cref="ICustomerService.DeactivateAsync(Guid)"/>.
///
/// Tags enable flexible segmentation—for example, marking customers as "vip",
/// "wholesale", or "beta-tester"—without requiring schema changes. The
/// <see cref="PreferredContact"/> property controls which channel is used for
/// outbound communications.
/// </remarks>
/// <example>
/// Creating a new customer with required properties:
/// <code language="csharp">
/// var customer = new Customer
/// {
///     Id = Guid.NewGuid(),
///     FullName = "Jane Doe",
///     Email = "jane.doe@example.com",
///     Tags = ["vip", "early-adopter"],
///     PreferredContact = ContactMethod.Email
/// };
/// </code>
/// </example>
/// <seealso cref="ICustomerService"/>
/// <seealso cref="Order"/>
/// <seealso cref="ContactMethod"/>
public class Customer
{
    /// <summary>
    /// Gets or sets the globally unique identifier for this customer.
    /// </summary>
    /// <remarks>
    /// This value is typically generated by the caller at construction time using
    /// <see cref="Guid.NewGuid()"/>. It serves as the primary key across all
    /// persistence layers and is immutable after creation.
    /// </remarks>
    public required Guid Id { get; set; }

    /// <summary>
    /// Gets or sets the customer's full display name.
    /// </summary>
    /// <remarks>
    /// This property is required and must not be <see langword="null"/> or whitespace.
    /// It is used throughout the UI and in transactional emails as the primary
    /// way to address the customer.
    /// </remarks>
    public required string FullName { get; set; }

    /// <summary>
    /// Gets or sets the customer's email address, used for account verification
    /// and transactional notifications.
    /// </summary>
    /// <remarks>
    /// When <see langword="null"/>, the customer has not provided an email and
    /// cannot receive email-based communications. Validation should enforce
    /// RFC 5322 format when a value is present.
    /// </remarks>
    public string? Email { get; set; }

    /// <summary>
    /// Gets or sets the UTC date and time when this customer record was created.
    /// </summary>
    /// <remarks>
    /// Automatically set to <see cref="DateTimeOffset.UtcNow"/> at construction.
    /// This value should not be modified after the initial persistence operation.
    /// </remarks>
    public DateTimeOffset CreatedAt { get; set; } = DateTimeOffset.UtcNow;

    /// <summary>
    /// Gets or sets a value indicating whether the customer account is currently active.
    /// </summary>
    /// <remarks>
    /// Inactive customers are excluded from search results and cannot place new orders.
    /// Use <see cref="ICustomerService.DeactivateAsync(Guid)"/> to set this to
    /// <see langword="false"/> in a controlled manner that also raises the appropriate
    /// domain events.
    /// </remarks>
    public bool IsActive { get; set; } = true;

    /// <summary>
    /// Gets or sets the list of free-form tags used for customer segmentation
    /// and targeted marketing campaigns.
    /// </summary>
    /// <remarks>
    /// Tags are case-insensitive string labels. Common conventions include
    /// lowercase kebab-case (e.g., "early-adopter", "high-value"). An empty
    /// list indicates that no segmentation has been applied.
    /// </remarks>
    /// <example>
    /// Adding a segmentation tag to an existing customer:
    /// <code language="csharp">
    /// customer.Tags.Add("loyalty-program");
    /// </code>
    /// </example>
    public List<string> Tags { get; set; } = [];

    /// <summary>
    /// Gets or sets the customer's preferred communication channel.
    /// </summary>
    /// <remarks>
    /// Defaults to <see cref="ContactMethod.Email"/>. When sending notifications,
    /// the system should honour this preference and fall back to email only when
    /// the preferred channel is unavailable.
    /// </remarks>
    /// <seealso cref="ContactMethod"/>
    public ContactMethod PreferredContact { get; set; } = ContactMethod.Email;
}

/// <summary>
/// Specifies the preferred communication channel for contacting a customer.
/// </summary>
/// <remarks>
/// This enumeration is used by the notification subsystem to select the
/// appropriate delivery mechanism. It is stored as its integer value in
/// the database and serialised as a string in JSON responses.
/// </remarks>
/// <seealso cref="Customer.PreferredContact"/>
public enum ContactMethod
{
    /// <summary>Contact via email. This is the default channel.</summary>
    Email = 0,

    /// <summary>Contact via a voice phone call.</summary>
    Phone = 1,

    /// <summary>Contact via short message service (SMS / text message).</summary>
    Sms = 2,

    /// <summary>Contact via physical postal mail.</summary>
    Mail = 3,
}

/// <summary>
/// Represents an order placed by a <see cref="Customer"/>, containing one or more
/// <see cref="OrderItem"/> line items and tracking lifecycle state through
/// <see cref="OrderStatus"/>.
/// </summary>
/// <remarks>
/// An <see cref="Order"/> is always associated with a single customer via
/// <see cref="CustomerId"/>. The order progresses through a linear state machine:
/// <see cref="OrderStatus.Pending"/> → <see cref="OrderStatus.Confirmed"/> →
/// <see cref="OrderStatus.Shipped"/> → <see cref="OrderStatus.Delivered"/>.
/// At any point before shipping, the order can transition to
/// <see cref="OrderStatus.Cancelled"/>.
///
/// The <see cref="TotalPrice"/> property is computed from the sum of each line item's
/// quantity multiplied by its unit price. It is not persisted and is recalculated
/// on every access.
/// </remarks>
/// <example>
/// Creating an order with two line items:
/// <code language="csharp">
/// var order = new Order
/// {
///     Id = Guid.NewGuid(),
///     CustomerId = customer.Id,
///     Items =
///     [
///         new OrderItem { ProductName = "Widget", Quantity = 3, UnitPrice = 9.99m },
///         new OrderItem { ProductName = "Gadget", Quantity = 1, UnitPrice = 24.95m }
///     ]
/// };
/// // order.TotalPrice == 54.92m
/// </code>
/// </example>
/// <seealso cref="Customer"/>
/// <seealso cref="OrderItem"/>
/// <seealso cref="OrderStatus"/>
/// <seealso cref="IOrderNotificationService"/>
public class Order
{
    /// <summary>
    /// Gets or sets the globally unique identifier for this order.
    /// </summary>
    public required Guid Id { get; set; }

    /// <summary>
    /// Gets or sets the identifier of the <see cref="Customer"/> who placed this order.
    /// </summary>
    /// <remarks>
    /// This is a foreign key reference. The referenced customer must exist and be active
    /// at the time the order is created.
    /// </remarks>
    public required Guid CustomerId { get; set; }

    /// <summary>
    /// Gets or sets the UTC date and time when the order was placed.
    /// </summary>
    public DateTimeOffset OrderDate { get; set; } = DateTimeOffset.UtcNow;

    /// <summary>
    /// Gets or sets the collection of line items that make up this order.
    /// </summary>
    /// <remarks>
    /// An order must contain at least one item to be valid. Each item captures a
    /// product name, quantity, and unit price at the time of purchase.
    /// </remarks>
    public List<OrderItem> Items { get; set; } = [];

    /// <summary>
    /// Gets the total price of the order, computed as the sum of each item's
    /// <see cref="OrderItem.Quantity"/> multiplied by its <see cref="OrderItem.UnitPrice"/>.
    /// </summary>
    /// <remarks>
    /// This is a calculated property and is not stored. It reflects the current state
    /// of the <see cref="Items"/> collection.
    /// </remarks>
    public decimal TotalPrice => Items.Sum(i => i.Quantity * i.UnitPrice);

    /// <summary>
    /// Gets or sets the current lifecycle status of the order.
    /// </summary>
    /// <remarks>
    /// Defaults to <see cref="OrderStatus.Pending"/>. State transitions should be
    /// performed through the order processing pipeline, which validates that each
    /// transition is legal and raises the corresponding event via
    /// <see cref="IOrderNotificationService"/>.
    /// </remarks>
    public OrderStatus Status { get; set; } = OrderStatus.Pending;
}

/// <summary>
/// Represents a single line item within an <see cref="Order"/>, capturing the product,
/// quantity, and price at the time of purchase.
/// </summary>
/// <remarks>
/// Prices are captured at order time and do not change if the product's catalogue
/// price is updated later. The line total can be calculated as
/// <c>Quantity * UnitPrice</c>.
/// </remarks>
/// <seealso cref="Order"/>
public class OrderItem
{
    /// <summary>
    /// Gets or sets the display name of the product being ordered.
    /// </summary>
    /// <remarks>
    /// This is a snapshot of the product name at order time. It is stored
    /// denormalized so that the order remains readable even if the product
    /// is renamed or removed from the catalogue.
    /// </remarks>
    public required string ProductName { get; set; }

    /// <summary>
    /// Gets or sets the number of units ordered.
    /// </summary>
    /// <remarks>
    /// Must be a positive integer. Defaults to 1.
    /// </remarks>
    public int Quantity { get; set; } = 1;

    /// <summary>
    /// Gets or sets the unit price of the product at the time the order was placed.
    /// </summary>
    /// <remarks>
    /// Stored as a <see cref="decimal"/> to avoid floating-point rounding errors
    /// in financial calculations.
    /// </remarks>
    public decimal UnitPrice { get; set; }
}

/// <summary>
/// Defines the lifecycle states an <see cref="Order"/> progresses through from
/// initial placement to final fulfilment or cancellation.
/// </summary>
/// <remarks>
/// The legal transitions form a linear pipeline with an escape hatch:
/// <see cref="Pending"/> → <see cref="Confirmed"/> → <see cref="Shipped"/> →
/// <see cref="Delivered"/>. An order may be moved to <see cref="Cancelled"/>
/// at any point before <see cref="Shipped"/>.
/// </remarks>
/// <seealso cref="Order.Status"/>
/// <seealso cref="IOrderNotificationService"/>
public enum OrderStatus
{
    /// <summary>The order has been created but has not yet been reviewed or confirmed.</summary>
    Pending = 0,

    /// <summary>Payment has been verified and the order is approved for fulfilment.</summary>
    Confirmed = 1,

    /// <summary>The order has left the warehouse and is in transit to the customer.</summary>
    Shipped = 2,

    /// <summary>The order has been received by the customer, completing the fulfilment cycle.</summary>
    Delivered = 3,

    /// <summary>The order was cancelled before shipment. Cancelled orders cannot be reinstated.</summary>
    Cancelled = 4,
}
