// Licensed to the .NET Foundation under one or more agreements.
// The .NET Foundation licenses this file to you under the MIT license.

using System.Collections.Immutable;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.Text;
using ApiContracts.Generator.Helpers;

namespace ApiContracts.Generator;

/// <summary>
/// Incremental source generator that emits deterministic, versioned JSON API schemas
/// for all public types in the compilation.
/// </summary>
[Generator(LanguageNames.CSharp)]
public sealed class ApiSchemaGenerator : IIncrementalGenerator
{
    /// <inheritdoc />
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        // Collect all named type symbols from the compilation
        var typeSymbols = context.CompilationProvider.Select(
            static (compilation, ct) =>
            {
                var types = new List<INamedTypeSymbol>();
                CollectTypes(compilation.GlobalNamespace, types, compilation, ct);
                return types.ToImmutableArray();
            });

        // Collect assembly-level config
        var assemblyConfig = context.CompilationProvider.Select(
            static (compilation, ct) =>
            {
                return ConfigExtractor.ExtractConfig(compilation.Assembly);
            });

        // Combine and generate
        var combined = typeSymbols.Combine(assemblyConfig)
            .Combine(context.CompilationProvider);

        context.RegisterSourceOutput(combined, static (spc, data) =>
        {
            var ((types, config), compilation) = data;
            Execute(spc, compilation, types, config);
        });
    }

    private static void Execute(
        SourceProductionContext context,
        Compilation compilation,
        ImmutableArray<INamedTypeSymbol> types,
        AssemblyConfig config)
    {
        if (types.IsDefaultOrEmpty)
        {
            return;
        }

        var assemblyName = compilation.AssemblyName ?? "Unknown";
        var assemblyVersion = compilation.Assembly.Identity.Version.ToString();

        // Build canonical model
        var modelBuilder = new CanonicalModelBuilder(compilation);
        var typeModels = modelBuilder.BuildTypes(types);

        // Compute deterministic hash
        var canonicalJson = CanonicalSerializer.SerializeForHashing(typeModels);
        var apiHash = HashComputer.ComputeSha256(canonicalJson);

        // Build assembly schema JSON
        var schemaJson = SchemaEmitter.EmitAssemblySchema(
            assemblyName,
            assemblyVersion,
            compilation.Options is CSharpCompilationOptions csharpOptions
                ? $"net{(csharpOptions.Platform == Platform.AnyCpu ? "10.0" : "10.0")}"
                : "net10.0",
            typeModels,
            apiHash,
            config);

        // Emit as additional file via source text
        context.AddSource(
            $"{assemblyName}.ai-schema.g.cs",
            SourceText.From(
                $$"""
                // <auto-generated/>
                // API Schema generated by ApiContracts.Generator
                // Assembly: {{assemblyName}}
                // Hash: {{apiHash}}
                // This file is generated and should not be edited manually.

                #if false
                // The JSON schema is emitted as an embedded resource.
                // See: ai-skills/apis/reference/{{assemblyName}}.ai-schema.json
                #endif
                """,
                Encoding.UTF8));

        // Emit the actual JSON schema as additional source
        context.AddSource(
            $"{assemblyName}.ai-schema.json.g.cs",
            SourceText.From(
                GenerateSchemaEmbedder(assemblyName, schemaJson),
                Encoding.UTF8));
    }

    private static string GenerateSchemaEmbedder(string assemblyName, string schemaJson)
    {
        var escaped = schemaJson.Replace("\"", "\"\"");
        return $$"""
            // <auto-generated/>
            namespace ApiContracts.Generated
            {
                internal static partial class EmbeddedSchemas
                {
                    /// <summary>
                    /// Gets the generated AI schema JSON for the {{assemblyName}} assembly.
                    /// </summary>
                    public static string {{SanitizeIdentifier(assemblyName)}}Schema => @"{{escaped}}";
                }
            }
            """;
    }

    private static string SanitizeIdentifier(string name) =>
        name.Replace(".", "").Replace("-", "").Replace(" ", "");

    private static void CollectTypes(
        INamespaceSymbol ns,
        List<INamedTypeSymbol> types,
        Compilation compilation,
        System.Threading.CancellationToken ct)
    {
        ct.ThrowIfCancellationRequested();

        foreach (var type in ns.GetTypeMembers())
        {
            if (type.DeclaredAccessibility == Accessibility.Public &&
                !IsCompilerGenerated(type))
            {
                types.Add(type);
            }
        }

        foreach (var childNs in ns.GetNamespaceMembers())
        {
            if (SymbolEqualityComparer.Default.Equals(childNs.ContainingAssembly, compilation.Assembly))
            {
                CollectTypes(childNs, types, compilation, ct);
            }
        }
    }

    private static bool IsCompilerGenerated(INamedTypeSymbol type)
    {
        return type.Name.StartsWith("<") ||
               type.GetAttributes().Any(a =>
                   a.AttributeClass?.Name == "CompilerGeneratedAttribute");
    }
}
